In [3]:
import numpy as np

x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
x = np.zeros((3,4), dtype = int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
x = np.full((4,5),13)
print(x)

[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]


In [8]:
x = np.eye(6)
print(x)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [9]:
x = np.diag((2,4,12,34))
print(x)

[[ 2  0  0  0]
 [ 0  4  0  0]
 [ 0  0 12  0]
 [ 0  0  0 34]]


In [10]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
x = np.arange(2,9)
print(x)

[2 3 4 5 6 7 8]


In [12]:
x = np.arange(2,9,2)
print(x)

[2 4 6 8]


In [17]:
x = np.linspace(0,26,10)
print(x)

[ 0.          2.88888889  5.77777778  8.66666667 11.55555556 14.44444444
 17.33333333 20.22222222 23.11111111 26.        ]
